services:
  poll:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - redis
    networks:
      - poll-net

  result:
    build:
      context: ./result
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=voting_db
    depends_on:
      - db
    networks:
      - poll-net

  redis:
    image: "redis:alpine" # This line is crucial
    networks:
      - poll-net

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=voting_db
    depends_on:
      - db
      - redis
    networks:
      - poll-net

  db:
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=voting_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - poll-net

volumes:
  db-data:

networks:
  poll-net:
    driver: bridge